"""create initial tables

Revision ID: 65e083fe5966
Revises: 
Create Date: 2026-04-22 17:12:48.401433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65e083fe5966'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devlens_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_devlens_users_email'), 'devlens_users', ['email'], unique=True)
    op.create_index(op.f('ix_devlens_users_user_id'), 'devlens_users', ['user_id'], unique=False)
    op.create_table('devlens_users_projects',
    sa.Column('projects_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['devlens_users.user_id'], ),
    sa.PrimaryKeyConstraint('projects_id')
    )
    op.create_index(op.f('ix_devlens_users_projects_projects_id'), 'devlens_users_projects', ['projects_id'], unique=False)
    op.create_table('devlens_users_scan_runs',
    sa.Column('scan_runs_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('uploaded_zip_path', sa.String(), nullable=True),
    sa.Column('extracted_path', sa.String(), nullable=True),
    sa.Column('total_files', sa.Integer(), nullable=True),
    sa.Column('supported_files', sa.Integer(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('issue_count', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['devlens_users_projects.projects_id'], ),
    sa.PrimaryKeyConstraint('scan_runs_id')
    )
    op.create_index(op.f('ix_devlens_users_scan_runs_scan_runs_id'), 'devlens_users_scan_runs', ['scan_runs_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devlens_users_scan_runs_scan_runs_id'), table_name='devlens_users_scan_runs')
    op.drop_table('devlens_users_scan_runs')
    op.drop_index(op.f('ix_devlens_users_projects_projects_id'), table_name='devlens_users_projects')
    op.drop_table('devlens_users_projects')
    op.drop_index(op.f('ix_devlens_users_user_id'), table_name='devlens_users')
    op.drop_index(op.f('ix_devlens_users_email'), table_name='devlens_users')
    op.drop_table('devlens_users')
    # ### end Alembic commands ###
