"""add embedding to file chunks

Revision ID: d533d99d44ef
Revises: c609bab0c60d
Create Date: 2026-05-18 16:38:50.332660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'd533d99d44ef'
down_revision: Union[str, Sequence[str], None] = 'c609bab0c60d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "file_chunks",
    sa.Column("embedding", Vector(1536), nullable=True)
)    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_chunks', 'embedding')
    # ### end Alembic commands ###
